name: status
description: A web app that report's my availability status.
publish_to: none
version: 0.0.1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: 0.18.1
  get_it: ^7.6.7
  equatable: ^2.0.5
  flutter_secure_storage: ^9.0.0
  shared_preferences: ^2.2.2
  provider: ^6.1.2
  rxdart: ^0.27.7
  flutter_dialog_manager: ^1.0.0+4
  dio: ^5.4.2+1
  url_launcher: ^6.2.5
  url_strategy: ^0.2.0
  google_fonts: ^6.2.1
  phosphor_flutter: ^2.0.1
  auto_size_text: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  flutter_lints: ^2.0.0
  mockito: ^5.4.4

flutter_gen:
  output: lib/core/assets
  assets:
    outputs:
      class_name: AppAssets
      package_parameter_enabled: false

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/
